// Code generated by MockGen. DO NOT EDIT.
// Source: spare_parts.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	api "github.com/adrienmazet/go-spare-parts-gateway/api"
	gomock "github.com/golang/mock/gomock"
)

// MockSparePartsRepo is a mock of SparePartsRepo interface.
type MockSparePartsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSparePartsRepoMockRecorder
}

// MockSparePartsRepoMockRecorder is the mock recorder for MockSparePartsRepo.
type MockSparePartsRepoMockRecorder struct {
	mock *MockSparePartsRepo
}

// NewMockSparePartsRepo creates a new mock instance.
func NewMockSparePartsRepo(ctrl *gomock.Controller) *MockSparePartsRepo {
	mock := &MockSparePartsRepo{ctrl: ctrl}
	mock.recorder = &MockSparePartsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSparePartsRepo) EXPECT() *MockSparePartsRepoMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockSparePartsRepo) GetById(id string) (*api.SparePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*api.SparePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockSparePartsRepoMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockSparePartsRepo)(nil).GetById), id)
}
