apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - metrics-server.yaml
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - kafka.yaml
  - providers.yaml
  - spare-parts-api.yaml
  - offer-price-worker.yaml
  - hpa.yaml
  - ingress.yaml
