// Code generated by MockGen. DO NOT EDIT.
// Source: spare_parts.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	api "github.com/adrienmazet/go-spare-parts-gateway/api"
	mapper "github.com/adrienmazet/go-spare-parts-gateway/internal/service/mapper"
	gomock "github.com/golang/mock/gomock"
)

// MockSparePartsService is a mock of SparePartsService interface.
type MockSparePartsService struct {
	ctrl     *gomock.Controller
	recorder *MockSparePartsServiceMockRecorder
}

// MockSparePartsServiceMockRecorder is the mock recorder for MockSparePartsService.
type MockSparePartsServiceMockRecorder struct {
	mock *MockSparePartsService
}

// NewMockSparePartsService creates a new mock instance.
func NewMockSparePartsService(ctrl *gomock.Controller) *MockSparePartsService {
	mock := &MockSparePartsService{ctrl: ctrl}
	mock.recorder = &MockSparePartsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSparePartsService) EXPECT() *MockSparePartsServiceMockRecorder {
	return m.recorder
}

// Mapper mocks base method.
func (m *MockSparePartsService) Mapper() mapper.SparePartsMapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mapper")
	ret0, _ := ret[0].(mapper.SparePartsMapper)
	return ret0
}

// Mapper indicates an expected call of Mapper.
func (mr *MockSparePartsServiceMockRecorder) Mapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mapper", reflect.TypeOf((*MockSparePartsService)(nil).Mapper))
}

// Retrieve mocks base method.
func (m *MockSparePartsService) Retrieve(ctx context.Context, reference string) (*api.SparePart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, reference)
	ret0, _ := ret[0].(*api.SparePart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockSparePartsServiceMockRecorder) Retrieve(ctx, reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockSparePartsService)(nil).Retrieve), ctx, reference)
}
