// Code generated by MockGen. DO NOT EDIT.
// Source: spare_parts.go

// Package mapper is a generated GoMock package.
package mapper

import (
	reflect "reflect"

	api "github.com/adrienmazet/go-spare-parts-gateway/api"
	gomock "github.com/golang/mock/gomock"
)

// MockSparePartsMapper is a mock of SparePartsMapper interface.
type MockSparePartsMapper struct {
	ctrl     *gomock.Controller
	recorder *MockSparePartsMapperMockRecorder
}

// MockSparePartsMapperMockRecorder is the mock recorder for MockSparePartsMapper.
type MockSparePartsMapperMockRecorder struct {
	mock *MockSparePartsMapper
}

// NewMockSparePartsMapper creates a new mock instance.
func NewMockSparePartsMapper(ctrl *gomock.Controller) *MockSparePartsMapper {
	mock := &MockSparePartsMapper{ctrl: ctrl}
	mock.recorder = &MockSparePartsMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSparePartsMapper) EXPECT() *MockSparePartsMapperMockRecorder {
	return m.recorder
}

// ModelToResponse mocks base method.
func (m *MockSparePartsMapper) ModelToResponse(sp api.SparePart) *api.SparePart {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelToResponse", sp)
	ret0, _ := ret[0].(*api.SparePart)
	return ret0
}

// ModelToResponse indicates an expected call of ModelToResponse.
func (mr *MockSparePartsMapperMockRecorder) ModelToResponse(sp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelToResponse", reflect.TypeOf((*MockSparePartsMapper)(nil).ModelToResponse), sp)
}
