// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for AmountCurrency.
const (
	AUD AmountCurrency = "AUD"
	BGN AmountCurrency = "BGN"
	BRL AmountCurrency = "BRL"
	CLP AmountCurrency = "CLP"
	CZK AmountCurrency = "CZK"
	DKK AmountCurrency = "DKK"
	EUR AmountCurrency = "EUR"
	GBP AmountCurrency = "GBP"
	HRK AmountCurrency = "HRK"
	HUF AmountCurrency = "HUF"
	PEN AmountCurrency = "PEN"
	PLN AmountCurrency = "PLN"
	RON AmountCurrency = "RON"
	SEK AmountCurrency = "SEK"
	USD AmountCurrency = "USD"
)

// Defines values for SparePartCategory.
const (
	BODY       SparePartCategory = "BODY"
	BRAKING    SparePartCategory = "BRAKING"
	ELECTRONIC SparePartCategory = "ELECTRONIC"
	ENGINE     SparePartCategory = "ENGINE"
	FILTERS    SparePartCategory = "FILTERS"
	FLUIDS     SparePartCategory = "FLUIDS"
	LIGHTING   SparePartCategory = "LIGHTING"
	SUSPENSION SparePartCategory = "SUSPENSION"
	TOOLS      SparePartCategory = "TOOLS"
	TYRES      SparePartCategory = "TYRES"
)

// AmountCurrency Three-letter ISO currency code
type AmountCurrency string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Detail string `json:"detail" validate:"required,min=1,max=1000"`
	Status int    `json:"status" validate:"gte=100,lte=599"`
	Title  string `json:"title" validate:"required,min=1,max=120"`
}

// Offer defines model for Offer.
type Offer struct {
	// Currency Three-letter ISO currency code
	Currency AmountCurrency `json:"currency" validate:"required,oneof=AUD BGN BRL CLP CZK DKK EUR GBP HRK HUF PEN PLN RON SEK USD"`

	// DeliveryDelay ISO 8601 duration string
	DeliveryDelay string `json:"deliveryDelay" validate:"required,min=2,max=32,iso8601duration"`

	// ID Unique offer identifier
	ID string `json:"id" validate:"required,startswith=off-,min=5,max=64"`

	// Price Price in the smallest currency unit, for example cents
	Price         int `json:"price" validate:"gte=0,lte=100000000"`
	StockQuantity int `json:"stockQuantity" validate:"gte=0,lte=1000000"`

	// Supplier Supplier name
	Supplier string `json:"supplier" validate:"required,min=1,max=120"`
}

// SparePart defines model for SparePart.
type SparePart struct {
	// Brand Spare part brand
	Brand    string            `json:"brand" validate:"required,min=1,max=80"`
	Category SparePartCategory `json:"category" validate:"required,oneof=BODY ENGINE BRAKING SUSPENSION ELECTRONIC LIGHTING TYRES FLUIDS FILTERS TOOLS"`

	// Description Spare part description
	Description string `json:"description" validate:"required,min=1,max=1000"`

	// ID Unique spare part identifier
	ID string `json:"id" validate:"required,startswith=sp-,min=4,max=64"`

	// Label Human-readable spare part label
	Label string `json:"label" validate:"required,min=1,max=160"`

	// Offers Supplier offers for this spare part
	Offers []Offer `json:"offers" validate:"required,max=100,dive"`

	// Reference Supplier or catalog reference
	Reference string `json:"reference" validate:"required,min=3,max=80,uppercase_ref"`
}

// SparePartCategory defines model for SparePartCategory.
type SparePartCategory string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RYbXPiOBL+KyrdfpjcmoQQkkqoSqUgEKDggOOlrnaS3JRiN6AdW/JKcjbcHP/9qiWD",
	"bcgxk92kNh8c4zd1P93P0936Rn0ZxVKAMJrWvlHtLyFi9rQeyUSY20QpEP4KrwSgfcVjw6WgNTpdKoBS",
	"CMaAIt3JkPjpo8SXAVCPgkgiWrun9VmTerTRHuBx3Kceve2P8Pi5Rz3a7OGxNRtTj7YbeL0zxiud2R31",
	"6KiFb436eBwP8Thp4d3ZpEkfPQovLIpDoLX0A2YV4w9tFBcL6tGXkmQxL6FBCxAleDGKlQxbWAefWcgD",
	"ZvAFBb8lXEHgSQFyfl2fNUmjPSCNcZ/c9kfk9nOPNHs90pqNSbsxIp1xj3Rmd2TUGpBRf0DGwwGZtHoE",
	"rVqvPdpSSqox6FgKDbhUrGQMynDQDkfDeIhnmf2TmCkgMVOG/M7NkiiYA6IJZDboDYb/GpTGrTsipCFz",
	"mYiAejRiL30QC7OktdNyuezRiIvthXeAIuLi+tSL2Ms1ft76pQ0ziS4YXi1XrSk8wmCfX11ZO9yvU7Qq",
	"tYMLAwtQbzBkYQBX9kID1+dXV9YAw00IReAG0pC7VyCpfCgiFQRk7W3vYZ4747YoeZs4P26Xlk+/gm/o",
	"2qPD+RzUfmb4Obb9pGBOa/RvJxlDT1J6nuxwc41rhfwZ1KoJIXuFrMjPy4vyKQkSxfAa2cKQQTmaVi87",
	"RRjPKgUUKx6NGRIev/nv0aeb64eH4L/Th4fg6NPDQ/Bz8+jm09SedY5u7P9/pP8nRzdHNz/Rd4pCxUbh",
	"rOJxLdGtjVc2SXiw7/9M8N8SIBJhJzwAYfic23TM3JfzealcPi0CcFEtAHBeAADfuGel/9RLn8ulq9KX",
	"x5/fxUNtmDIaZeAaV7Aen1uPL6rWw1hxH/adHOFlwgUxSyA6YmEI2mSynAhuPDKXiqQ+E9/Kfg6DqiPw",
	"hs5IfPuXI/WfpbQj9PbLqa5I/+s/EyYMN6uivFT2zfkoY5wpSRyH3HGziO4kvUMEi6DIGwzXSMm/XIE4",
	"iuDWg02eeJms7EK9qxuvSZWtTOjivlw9KSZeIVuulrkn8mA1FERPO1BdfiRSly6wPjOwkOq70rp193bz",
	"glXXnH8H3M3fyDvd4YsliUHNpYoYFvW5ksKi8xXfDLSlZaKemCBMBGTJF8vf2YokGv6aSn9AQ3Xm7v8R",
	"Uh1/V0erBR3V8QfLqI6dilbzKhqyJwj33ewkERMlBSxgT2HBXfdC3tM7G8aGDeOIBXonWBcfGqsLFypb",
	"0/QBvXIP2AwzS65zHlGPcgOR/h4nXLeyts513Qv53o4pxVZ/yBmXcl7An4E6MUu73kPuKOIzw0K5yJrk",
	"osKMe6VRvVmqnldOD+rMWSEJ7136Pd5v0/Dv79avnKVK5CVxDMpnGr4g3K8LeN6rTcptdHSrYkVN2mbB",
	"QQG/zUngZjhrDJu/4Pw1aHcHLTug1XvdQRsHrdlk1BpMunbqavVbt9PxcNC9pR7td9udqXto+su4NaEe",
	"vevPuk170u1PW2M8mw6H/UlxSMs+/k6DGlpPnO0k/TjJ7CaZ1WRjM7EWE2cvSa0lzta1jQcXc7mffnWr",
	"yaW8hrclqY+6hC0WChbMcLEgISyYvyIsMTKShj8D2VRjTQJm2PEDxiqdYtLCYbsH0mYGUPHroy716DMo",
	"7dY9PS4flzGKMgbBYk5r9Oy4fIyJHTOztPicWEaXkNEn37bZs8ZbC7BlG4u2bZC7Aa3RNphtTjRW41y6",
	"xUyxCIzVk/sDdS6fohzvoS3Uo7Y1qhUyOEtvoxLw0h2G4gy3w9i3knK9fsR13LhtEamUy3acksKAsAgw",
	"DINvMTj5VbsynhqwaWW+whcsxXYbJIkihkTZm8s1PINi4TauqbpizFiYQK4ryjqdrPXIMWCn6PypBgGr",
	"dVZ107r2WnHa1Ir7/KiZ7p3sTJDbadB+PJuN0tnDTQo7jTt261kDnfXFa+9H1jtrFlerZKudXb2y2mVh",
	"sXpi5AQfoC4btoWkmF2W4lkO/lAn6F46QAajODxDQHTi+6D1PAlD2zZWy9U3pqGQ5ovb4HG6l0B+w+gP",
	"7BJttmzsPs1GeLI9kzfAUdzUOgxJZsHao+c/RMZ3MqIrUDqQoKCeQRHAF9LJbsPpcRowwvLd3dMqJ2sO",
	"F/sJR5dEIf5LY+LayUkofRYupTa1yzKOF4/r/wUAAP//y1CNv0gVAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
