// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for AmountCurrency.
const (
	AUD AmountCurrency = "AUD"
	BGN AmountCurrency = "BGN"
	BRL AmountCurrency = "BRL"
	CLP AmountCurrency = "CLP"
	CZK AmountCurrency = "CZK"
	DKK AmountCurrency = "DKK"
	EUR AmountCurrency = "EUR"
	GBP AmountCurrency = "GBP"
	HRK AmountCurrency = "HRK"
	HUF AmountCurrency = "HUF"
	PEN AmountCurrency = "PEN"
	PLN AmountCurrency = "PLN"
	RON AmountCurrency = "RON"
	SEK AmountCurrency = "SEK"
	USD AmountCurrency = "USD"
)

// Defines values for SparePartCategory.
const (
	BODY       SparePartCategory = "BODY"
	BRAKING    SparePartCategory = "BRAKING"
	ELECTRONIC SparePartCategory = "ELECTRONIC"
	ENGINE     SparePartCategory = "ENGINE"
	FILTERS    SparePartCategory = "FILTERS"
	FLUIDS     SparePartCategory = "FLUIDS"
	LIGHTING   SparePartCategory = "LIGHTING"
	SUSPENSION SparePartCategory = "SUSPENSION"
	TOOLS      SparePartCategory = "TOOLS"
	TYRES      SparePartCategory = "TYRES"
)

// AmountCurrency Three-letter ISO currency code
type AmountCurrency string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Detail string `json:"detail" validate:"required,min=1,max=1000"`
	Status int    `json:"status" validate:"gte=100,lte=599"`
	Title  string `json:"title" validate:"required,min=1,max=120"`
}

// Offer defines model for Offer.
type Offer struct {
	// Currency Three-letter ISO currency code
	Currency AmountCurrency `json:"currency" validate:"required,oneof=AUD BGN BRL CLP CZK DKK EUR GBP HRK HUF PEN PLN RON SEK USD"`

	// DeliveryDelay ISO 8601 duration string
	DeliveryDelay string `json:"deliveryDelay" validate:"required,min=2,max=32,iso8601duration"`

	// ID Unique offer identifier
	ID string `json:"id" validate:"required,startswith=off-,min=5,max=64"`

	// Price Price in the smallest currency unit, for example cents
	Price         int `json:"price" validate:"gte=0,lte=100000000"`
	StockQuantity int `json:"stockQuantity" validate:"gte=0,lte=1000000"`

	// Supplier Supplier name
	Supplier string `json:"supplier" validate:"required,min=1,max=120"`
}

// SparePart defines model for SparePart.
type SparePart struct {
	// Brand Spare part brand
	Brand    string            `json:"brand" validate:"required,min=1,max=80"`
	Category SparePartCategory `json:"category" validate:"required,oneof=BODY ENGINE BRAKING SUSPENSION ELECTRONIC LIGHTING TYRES FLUIDS FILTERS TOOLS"`

	// Description Spare part description
	Description string `json:"description" validate:"required,min=1,max=1000"`

	// ID Unique spare part identifier
	ID string `json:"id" validate:"required,startswith=sp-,min=4,max=64"`

	// Label Human-readable spare part label
	Label string `json:"label" validate:"required,min=1,max=160"`

	// Offers Supplier offers for this spare part
	Offers []Offer `json:"offers" validate:"required,max=100,dive"`

	// Reference Supplier or catalog reference
	Reference string `json:"reference" validate:"required,min=3,max=80,uppercase_ref"`
}

// SparePartCategory defines model for SparePartCategory.
type SparePartCategory string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RYbVPjOBL+KyrdfhhuHQghUCRVFJWQkKSSC7m8fNgBbkrYHUc7tuSVZJbcXP77Vcvv",
	"wGaGXajlg3FsS91PvzzdrW/UlWEkBQijafsb1e4GQmZvO6GMhbmKlQLhbvGJB9pVPDJcCtqmy40CqAVg",
	"DCgyWtwQN/2UuNID6lAQcUjbt7Sz6lGHdgdTvM4n1KFXkxleP4+pQ3tjvPZXc+rQQRefD+f4ZLi6pg6d",
	"9XHVbILX+Q1eF318u1r06L1D4YmFUQC0nW5gthH+0EZx4VOHPtUki3gNFfJB1ODJKFYzzLcAH1nAPWZw",
	"gYLfYq7Ac6QAub7orHqkO5iS7nxCriYzcvV5THrjMemv5mTQnZHhfEyGq2sy60/JbDIl85spWfTHBLXa",
	"7RzaV0qqOehICg0oKlIyAmU46MSOhvEA7wr9FxFTQCKmDPmdmw3hHtFRrdVqESENWctYeNShIXuagPDN",
	"hraP6/W6Q0Mu8gfvAD/k4uLYCdnTBW5vsWjDTKwryjbrTasKD9HBp62W1SP5dYxapXpwYcAH9QZFfAMo",
	"2QkMXJy2WlYBw00AVWNNpSHXr5ik8aEWaaBBdk7+DmM7US63kpP59j4XLR9+BdfQnUNv1mtQL6PBLWXY",
	"TwrWtE3/cVRk5VGakkfP8nGHsgL+CGrbg4C9kqCYk+dn9WPixYrhM5KboTDlbNk8H1bNeNKoWLHh0Ihh",
	"kuOe/5l9ury4u/P+t7y78w4+3d15P/cOLj8t7d3w4NL+/1f6f3FweXD5E30nLzSsF04aDtcSYWWobJBw",
	"7yX+leC/xUAkmp1wD4Tha27DsYAv1+tavX5cNcBZs2KA04oBcMUtq/23U/tcr7VqX+5/fheE2jBlNKb+",
	"BUqwiE8t4rOmRRgp7sJLkDN8TLggZgNEhywIQJuCimPBjUPWUpEUM3Et1Zds0EwSOEtnTHz7V0rqv5rS",
	"SULnO6e8It2v/46ZMNxsq/TSeKnORymTqBJHUcCT3Kxad5G+IYKFUM0bdNdMyb+dgTiSYI4gixOnoJXn",
	"pn7OG69Rla1GCPElXT0oJl5JtlL9Sr4oG6urIHx4Zqrzj7TUeeJYlxnwpfouteZwr7IFll1L+PbALb8o",
	"gx5yf0MiUGupQiZcIGslhbXOV1zpaZuWsXpggjDhkQ33N7+zLYk1/D2Vfg+H6gLuHxCpjr7Lo80Kj+ro",
	"g2lURwmLNsssGrAHCF7CHMYhEzUFzGMPQQVusqCM9Nq6sWvdOGOefuassw/11VniKlvT9B6+Sj6wEWY2",
	"XJcQUYdyA6H+Xk4k3crOghslC8q9HVOKbf8UmCTkHI8/Ak3IbA3IVLAPjiIuMyyQPik+rzDMfFybdXq1",
	"5mnjeC/PnFSC8DYJv/vbPAz/+W79yknKRE4cRaBcpuELmvt1Ai+jykIu49GcxaqclEfBXgK/KlFgNpB1",
	"b3q/4Mw1HYymfTuUdcaj6QCHq9Vi1p8uRnbS6k/6V8v5zXR0RR06GQ2Gy+Sj5S/z/oI69HqyGvXszWiy",
	"7M/xbnlzM1lUB7Ni83cazlB7kuhO0s1JoTcptCaZzsRqTBJ9SaotSXTdWX9wsZYvw69jOblW5vCBJJ3Z",
	"iDDfV+Azw4VPAvCZuyUsNjKUhj8CyaqxJh4z7PAOfZVOMWnhsN0DGTADyPid2Yg69BGUTuQeH9YP6+hF",
	"GYFgEadtenJYP8TAjpjZWPsc2YyuYUYffePeDp/5YOs1VmvbGY882qYDMHkwdLejnt1EsRCMZZDbPZWt",
	"QvUcX6J46lDbDbWzyM1C2agYnPQEoTqv5cXhbfy/293j/skYbVE36nU7MklhQFiwDE3tWrhHv+qkVKeC",
	"s3blK3zBcmuPN+IwZJgML+ZtDY+gWJD7LmVQ9AsLYih1PkU3U7QXpSh/Vlj+UhOAFbkwXlq7XitAWT24",
	"LY+T6ZnIsykxn/js5sX8k84XyTTwrDnHjrxokoved+f8iLyTXlVao5B20npF2nlFWCc2coEf0CQa8mJR",
	"5XybxkXs/VC3lyz6w/BXYBSHR/CIjl0XtF7HQWBbw2a9+cYwFNJ8SQ5xEm6LoXwQ9IOnP9lRjD1/yQil",
	"OAt5gwmqB1T7zVBosHPo6Q8l4DspMRJIFpiUoB5BEcAF6cSW5fE8dRJh5a7tYUtGvdQgdm2SG7FCY2+M",
	"idpHR4F0WbCR2rTP6zgv3O/+HwAA//8rqIPnDRUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
